spring:
  application:
    name: "${SPRING_APPLICATION_NAME}"
  cloud:
    gateway:
      routes:
        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**
        - id: RESERVATION-SERVICE
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**, /bookings/**, /customer/**, /roomtype/**, /rooms/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
        - id: RESTAURANT-ORDER-SERVICE
          uri: lb://RESTAURANT-ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: VIRTUAL-WAITER-SERVICE
          uri: lb://VIRTUAL-WAITER-SERVICE
          predicates:
            - Path=/vw/**
  config:
    import: "optional:${SPRING_CONFIG_IMPORT}"


server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:cert/certificate.p12
    key-store-password: luxury