spring:
  application:
    name: "${SPRING_APPLICATION_NAME}"
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**
        - id: RESERVATION-SERVICE
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
        - id: RESTAURANT-ORDER-SERVICE
          uri: lb://RESTAURANT-ORDER-SERVICE
          predicates:
            - Path=/order/**
  config:
    import: "optional:${SPRING_CONFIG_IMPORT}"