apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/impressive-tome-429713-e9/locations/us-central1-c/clusters/hrmis-cluster-1